### ISSUE TITLE
Scheduler can't connect to database

### ISSUE THREAD

**Issue by BertCatsburg** [bitnami/bitnami-docker-airflow-scheduler#13]
### Name and Version

docker.io/bitnami/airflow-scheduler:2

### What steps will reproduce the bug?

1. Take docker-compose.yml file below and put it somewhere
2. In parent folder create empty dirs 'database' and 'redis'
3. Create docker-network as specified below
4. Start up the containers with 'docker-compose up'
5. At a certain moment you see the error about Scheduler which can't connect to the database

### What is the expected behavior?

Scheduler should connect to database.

### What do you see instead?

```bash
AirflowScheduler     | airflow-scheduler 13:28:14.12
AirflowScheduler     | airflow-scheduler 13:28:14.13 Welcome to the Bitnami airflow-scheduler container
AirflowScheduler     | airflow-scheduler 13:28:14.13 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-airflow-scheduler
AirflowScheduler     | airflow-scheduler 13:28:14.13 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-airflow-scheduler/issues
AirflowScheduler     | airflow-scheduler 13:28:14.13
AirflowScheduler     | airflow-scheduler 13:28:14.14 INFO  ==> Enabling non-root system user with nss_wrapper
AirflowScheduler     | airflow-scheduler 13:28:14.14 INFO  ==> ** Starting Airflow setup **
AirflowScheduler     | airflow-scheduler 13:28:14.21 INFO  ==> No injected configuration file found. Creating default config file
AirflowScheduler     | airflow-scheduler 13:28:15.06 INFO  ==> Configuring Airflow database
AirflowScheduler     | airflow-scheduler 13:28:15.09 INFO  ==> Configuring Celery Executor
AirflowScheduler     | airflow-scheduler 13:28:15.11 INFO  ==> Trying to connect to the database server
AirflowScheduler     | airflow-scheduler 13:29:21.94 ERROR ==> Could not connect to the database
```

### docker-compose.yml file
```yml
version: '3.9'

services:

  postgresql:
    image: docker.io/bitnami/postgresql:10
    volumes:
      - 'postgresql_data:/bitnami/postgresql'
    container_name: AirflowDb
    environment:
      - POSTGRESQL_DATABASE=bitnami_airflow
      - POSTGRESQL_USERNAME=bn_airflow
      - POSTGRESQL_PASSWORD=bitnami1
      - ALLOW_EMPTY_PASSWORD=no
    networks:
      my-net:
        ipv4_address: 172.30.2.1

  redis:
    image: docker.io/bitnami/redis:6.0
    volumes:
      - 'redis_data:/bitnami'
    container_name: AirflowRedis
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    networks:
      my-net:
        ipv4_address: 172.30.2.2

  airflow-scheduler:
    image: docker.io/bitnami/airflow-scheduler:2
    environment:
      - AIRFLOW_FERNET_KEY=wrfhjf9ertuivkfjaeioufbver
      - AIRFLOW_SECRET_KEY=345etgdfGerTGe5fgdfgdge5TdfgdfgbGfe
      - AIRFLOW_EXECUTOR=CeleryExecutor
      - AIRFLOW_DATABASE_NAME=bitnami_airflow
      - AIRFLOW_DATABASE_USERNAME=bn_airflow
      - AIRFLOW_DATABASE_PASSWORD=bitnami1
      - AIRFLOW_DATABASE_HOST=172.30.2.1
      - AIRFLOW_WEBSERVER_HOST=airflow
      - REDIS_HOST=172.30.2.2
    container_name: AirflowScheduler
    depends_on:
      - postgresql
      - redis
    networks:
      my-net:
        ipv4_address: 172.30.2.3

  airflow-worker:
    image: docker.io/bitnami/airflow-worker:2
    environment:
      - AIRFLOW_DATABASE_NAME=bitnami_airflow
      - AIRFLOW_DATABASE_USERNAME=bn_airflow
      - AIRFLOW_DATABASE_PASSWORD=bitnami1
      - AIRFLOW_DATABASE_HOST=172.30.2.1
      - AIRFLOW_FERNET_KEY=wrfhjf9ertuivkfjaeioufbver
      - AIRFLOW_SECRET_KEY=345etgdfGerTGe5fgdfgdge5TdfgdfgbGfe
      - AIRFLOW_EXECUTOR=CeleryExecutor
      - AIRFLOW_WEBSERVER_HOST=airflow
      - REDIS_HOST=172.30.2.2
    container_name: AirflowWorked_1
    depends_on:
      - postgresql
      - redis
    networks:
      my-net:
        ipv4_address: 172.30.2.40

  airflow-webserver:
    image: docker.io/bitnami/airflow:2
    environment:
      - AIRFLOW_DATABASE_NAME=bitnami_airflow
      - AIRFLOW_DATABASE_USERNAME=bn_airflow
      - AIRFLOW_DATABASE_PASSWORD=bitnami1
      - AIRFLOW_DATABASE_HOST=172.30.2.1
      - AIRFLOW_FERNET_KEY=wrfhjf9ertuivkfjaeioufbver
      - AIRFLOW_SECRET_KEY=345etgdfGerTGe5fgdfgdge5TdfgdfgbGfe
      - AIRFLOW_EXECUTOR=CeleryExecutor
      - AIRFLOW_USERNAME=myflow
      - AIRFLOW_PASSWORD=bitnamipassword
      - REDIS_HOST=172.30.2.2
    container_name: AirflowWebserver
    depends_on:
      - postgresql
      - redis
    ports:
      - '8080:8080'
    networks:
      my-net:
        ipv4_address: 172.30.2.4

volumes:
  postgresql_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ../database
  redis_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ../redis

networks:
  my-net:
    external: true
    name: my-net

```

### creating the docker network
```bash
docker network create \
    --driver=bridge \
    --subnet=172.30.0.0/16 \
    --attachable \
    --gateway=172.30.0.1 \
    my-net
```

### Additional info on the compose file
- I've added container_names to all containers
- All containers are running on external network my-net. 
- All container therefore have a IP address
- Connection to the database goes via IP address as mentioned in AIRFLOW_DATABASE_HOST
  (I do this in other projects and it's perfectly possible to connect to a database like this)
- Database port is not touched but in 'docker ps' I see that default 5432 is exposed
